name: Build & Test (Typescript)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    name: Build and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install dependencies
        run: yarn install
        working-directory: typescript
        
      - name: Execute build.sh script
        run: |
          cd typescript
          ./build.sh